### ISSUE TITLE
Leshan ignores Single-value web UI option on write

### ISSUE THREAD

**Issue by rlubos** [eclipse/leshan#894]
Hello Leshan community! Thank you for this great project 👍 

I've been testing Zephyr LwM2M client with Leshan public server (https://leshan.eclipseprojects.io/) and I've noticed some unexpected behaviour when writing to a single resource from Leshan web UI. The server seems to ignore the Content-Format value configured in the Single-value choice list of the UI:

![image](https://user-images.githubusercontent.com/22167799/93769508-28614000-fc1b-11ea-80cd-83d0e2fd9424.png)

I've verified with Wireshark, and the server appears to set `Content-Format` option to `application/vnd.oma.lwm2m+tlv` when writing to a single resource, regardless of the selected format. Single-value reads work as expected though, the `Accept` option is set accordingly to the Single-value field.

Moreover, I've noticed that when I change the format in Multi-value field to JSON, the server then performs writes on a single resource with `Content-Format` set to `application/vnd.oma.lwm2m+json`. Perhaps there's some mixup here, regarding the UI config option chosen for writes?

**Comment by sbernard31** [comment]
Hi @rlubos, 

   Thx a lot to reporting this :pray:  !
   
   You was right and this should be fixed in master and on the [sandbox](https://leshan.eclipseprojects.io/).
   Let me know if it's works for you now :pray:

**Comment by rlubos** [comment]
Thanks @sbernard31 for a quick fix! The Content-Format selection works fine now 👍 

But now I've faced one other issue. I've tried to run PUSH FOTA, by writing to Package resource of Firmware Update object (`5/0/0`). I've already done this with TLV data format, which works fine, but now using `application/octet-stream` (Opaque) as data format I end up with the following:
![image](https://user-images.githubusercontent.com/22167799/93793868-ad5a5280-fc37-11ea-90ca-7e06d3e68463.png)
I assume this should not happen for the Package resource, which is of Opaque data type?

**Comment by sbernard31** [comment]
I will look at this tomorrow !

**Comment by sbernard31** [comment]
@rlubos thx again for reporting this :pray: Do not hesitate to share if you find more !

The last bug you reported should be fixed in master and on the [sandbox](https://leshan.eclipseprojects.io).
This was a regression in server-demo caused by improvement (more checks) in core lib.
The way I fix it is more a HACK than a real clean solution.
The clean way is probably to change the json serialization/deserialization but without surprise **demo** are clearly not the priority. (There is so many changes I would like to make in demos :sweat:)

**Comment by rlubos** [comment]
Thank you for the quick fix, again 👍 I've just tested and I can confirm that Opaque Content-Format works as expected when running PUSH FOTA.

I totally understand that demos are only demos, but it's good to see it's fully functional now. It's really helpful for testing our embedded LwM2M client implementation in Zephyr RTOS. I'll surely show up here if I run into some other issues 😄

**Comment by rlubos** [comment]
Issues resolved.

**Comment by haoranx91** [comment]
Hi @sbernard31, I have the server demo running locally on a Linux machine, and I'm still seeing the same issue in version 1.2.0. Is this fix only applied to the public server?

**Comment by sbernard31** [comment]
Both fixes were backported in v1.x before the release : 
- commit (c42d7a4476ae5ddbcbfaa805c88d77d157cdaea0)
- commit (4ffd9b4b9ff8af39955303cc65e57484f53f7a78)

So it should be fixed in v1.2.0.

**Comment by sbernard31** [comment]
Just tested right now, and it works for me.

Please describe how to reproduce the issue ! This is maybe another bug.
